
CREATE TABLE `country_codes` (
    `id` CHAR(36) NOT NULL PRIMARY KEY,
    `country_name` VARCHAR(100) NOT NULL,
    `country_code` VARCHAR(10) NOT NULL
);

INSERT INTO `country_codes` (`id`, `country_name`, `country_code`) VALUES
    (UUID(), 'Afghanistan', '+93'),
    (UUID(), 'Albania', '+355'),
    (UUID(), 'Algeria', '+213'),
    (UUID(), 'Andorra', '+376'),
    (UUID(), 'Angola', '+244'),
    (UUID(), 'Antigua and Barbuda', '+1-268'),
    (UUID(), 'Argentina', '+54'),
    (UUID(), 'Armenia', '+374'),
    (UUID(), 'Australia', '+61'),
    (UUID(), 'Austria', '+43'),
    (UUID(), 'Azerbaijan', '+994'),
    (UUID(), 'Bahamas', '+1-242'),
    (UUID(), 'Bahrain', '+973'),
    (UUID(), 'Bangladesh', '+880'),
    (UUID(), 'Barbados', '+1-246'),
    (UUID(), 'Belarus', '+375'),
    (UUID(), 'Belgium', '+32'),
    (UUID(), 'Belize', '+501'),
    (UUID(), 'Benin', '+229'),
    (UUID(), 'Bhutan', '+975'),
    (UUID(), 'Bolivia', '+591'),
    (UUID(), 'Bosnia and Herzegovina', '+387'),
    (UUID(), 'Botswana', '+267'),
    (UUID(), 'Brazil', '+55'),
    (UUID(), 'Brunei', '+673'),
    (UUID(), 'Bulgaria', '+359'),
    (UUID(), 'Burkina Faso', '+226'),
    (UUID(), 'Burundi', '+257'),
    (UUID(), 'Cabo Verde', '+238'),
    (UUID(), 'Cambodia', '+855'),
    (UUID(), 'Cameroon', '+237'),
    (UUID(), 'Canada', '+1'),
    (UUID(), 'Central African Republic', '+236'),
    (UUID(), 'Chad', '+235'),
    (UUID(), 'Chile', '+56'),
    (UUID(), 'China', '+86'),
    (UUID(), 'Colombia', '+57'),
    (UUID(), 'Comoros', '+269'),
    (UUID(), 'Congo, Democratic Republic of the', '+243'),
    (UUID(), 'Congo, Republic of the', '+242'),
    (UUID(), 'Costa Rica', '+506'),
    (UUID(), 'Croatia', '+385'),
    (UUID(), 'Cuba', '+53'),
    (UUID(), 'Cyprus', '+357'),
    (UUID(), 'Czech Republic', '+420'),
    (UUID(), 'Denmark', '+45'),
    (UUID(), 'Djibouti', '+253'),
    (UUID(), 'Dominica', '+1-767'),
    (UUID(), 'Dominican Republic', '+1-809'),
    (UUID(), 'East Timor', '+670'),
    (UUID(), 'Ecuador', '+593'),
    (UUID(), 'Egypt', '+20'),
    (UUID(), 'El Salvador', '+503'),
    (UUID(), 'Equatorial Guinea', '+240'),
    (UUID(), 'Eritrea', '+291'),
    (UUID(), 'Estonia', '+372'),
    (UUID(), 'Eswatini', '+268'),
    (UUID(), 'Ethiopia', '+251'),
    (UUID(), 'Fiji', '+679'),
    (UUID(), 'Finland', '+358'),
    (UUID(), 'France', '+33'),
    (UUID(), 'Gabon', '+241'),
    (UUID(), 'Gambia', '+220'),
    (UUID(), 'Georgia', '+995'),
    (UUID(), 'Germany', '+49'),
    (UUID(), 'Ghana', '+233'),
    (UUID(), 'Greece', '+30'),
    (UUID(), 'Grenada', '+1-473'),
    (UUID(), 'Guatemala', '+502'),
    (UUID(), 'Guinea', '+224'),
    (UUID(), 'Guinea-Bissau', '+245'),
    (UUID(), 'Guyana', '+592'),
    (UUID(), 'Haiti', '+509'),
    (UUID(), 'Honduras', '+504'),
    (UUID(), 'Hungary', '+36'),
    (UUID(), 'Iceland', '+354'),
    (UUID(), 'India', '+91'),
    (UUID(), 'Indonesia', '+62'),
    (UUID(), 'Iran', '+98'),
    (UUID(), 'Iraq', '+964'),
    (UUID(), 'Ireland', '+353'),
    (UUID(), 'Israel', '+972'),
    (UUID(), 'Italy', '+39'),
    (UUID(), 'Jamaica', '+1-876'),
    (UUID(), 'Japan', '+81'),
    (UUID(), 'Jordan', '+962'),
    (UUID(), 'Kazakhstan', '+7'),
    (UUID(), 'Kenya', '+254'),
    (UUID(), 'Kiribati', '+686'),
    (UUID(), 'Korea, North', '+850'),
    (UUID(), 'Korea, South', '+82'),
    (UUID(), 'Kosovo', '+383'),
    (UUID(), 'Kuwait', '+965'),
    (UUID(), 'Kyrgyzstan', '+996'),
    (UUID(), 'Laos', '+856'),
    (UUID(), 'Latvia', '+371'),
    (UUID(), 'Lebanon', '+961'),
    (UUID(), 'Lesotho', '+266'),
    (UUID(), 'Liberia', '+231'),
    (UUID(), 'Libya', '+218'),
    (UUID(), 'Liechtenstein', '+423'),
    (UUID(), 'Lithuania', '+370'),
    (UUID(), 'Luxembourg', '+352'),
    (UUID(), 'Madagascar', '+261'),
    (UUID(), 'Malawi', '+265'),
    (UUID(), 'Malaysia', '+60'),
    (UUID(), 'Maldives', '+960'),
    (UUID(), 'Mali', '+223'),
    (UUID(), 'Malta', '+356'),
    (UUID(), 'Marshall Islands', '+692'),
    (UUID(), 'Mauritania', '+222'),
    (UUID(), 'Mauritius', '+230'),
    (UUID(), 'Mexico', '+52'),
    (UUID(), 'Micronesia', '+691'),
    (UUID(), 'Moldova', '+373'),
    (UUID(), 'Monaco', '+377'),
    (UUID(), 'Mongolia', '+976'),
    (UUID(), 'Montenegro', '+382'),
    (UUID(), 'Morocco', '+212'),
    (UUID(), 'Mozambique', '+258'),
    (UUID(), 'Myanmar', '+95'),
    (UUID(), 'Namibia', '+264'),
    (UUID(), 'Nauru', '+674'),
    (UUID(), 'Nepal', '+977'),
    (UUID(), 'Netherlands', '+31'),
    (UUID(), 'New Zealand', '+64'),
    (UUID(), 'Nicaragua', '+505'),
    (UUID(), 'Niger', '+227'),
    (UUID(), 'Nigeria', '+234'),
    (UUID(), 'North Macedonia', '+389'),
    (UUID(), 'Norway', '+47'),
    (UUID(), 'Oman', '+968'),
    (UUID(), 'Pakistan', '+92'),
    (UUID(), 'Palau', '+680'),
    (UUID(), 'Palestine', '+970'),
    (UUID(), 'Panama', '+507'),
    (UUID(), 'Papua New Guinea', '+675'),
    (UUID(), 'Paraguay', '+595'),
    (UUID(), 'Peru', '+51'),
    (UUID(), 'Philippines', '+63'),
    (UUID(), 'Poland', '+48'),
    (UUID(), 'Portugal', '+351'),
    (UUID(), 'Qatar', '+974'),
    (UUID(), 'Romania', '+40'),
    (UUID(), 'Russia', '+7'),
    (UUID(), 'Rwanda', '+250'),
    (UUID(), 'Saint Kitts and Nevis', '+1-869'),
    (UUID(), 'Saint Lucia', '+1-758'),
    (UUID(), 'Saint Vincent and the Grenadines', '+1-784'),
    (UUID(), 'Samoa', '+685'),
    (UUID(), 'San Marino', '+378'),
    (UUID(), 'Sao Tome and Principe', '+239'),
    (UUID(), 'Saudi Arabia', '+966'),
    (UUID(), 'Senegal', '+221'),
    (UUID(), 'Serbia', '+381'),
    (UUID(), 'Seychelles', '+248'),
    (UUID(), 'Sierra Leone', '+232'),
    (UUID(), 'Singapore', '+65'),
    (UUID(), 'Slovakia', '+421'),
    (UUID(), 'Slovenia', '+386'),
    (UUID(), 'Solomon Islands', '+677'),
    (UUID(), 'Somalia', '+252'),
    (UUID(), 'South Africa', '+27'),
    (UUID(), 'South Sudan', '+211'),
    (UUID(), 'Spain', '+34'),
    (UUID(), 'Sri Lanka', '+94'),
    (UUID(), 'Sudan', '+249'),
    (UUID(), 'Suriname', '+597'),
    (UUID(), 'Sweden', '+46'),
    (UUID(), 'Switzerland', '+41'),
    (UUID(), 'Syria', '+963'),
    (UUID(), 'Taiwan', '+886'),
    (UUID(), 'Tajikistan', '+992'),
    (UUID(), 'Tanzania', '+255'),
    (UUID(), 'Thailand', '+66'),
    (UUID(), 'Togo', '+228'),
    (UUID(), 'Tonga', '+676'),
    (UUID(), 'Trinidad and Tobago', '+1-868'),
    (UUID(), 'Tunisia', '+216'),
    (UUID(), 'Turkey', '+90'),
    (UUID(), 'Turkmenistan', '+993'),
    (UUID(), 'Tuvalu', '+688'),
    (UUID(), 'Uganda', '+256'),
    (UUID(), 'Ukraine', '+380'),
    (UUID(), 'United Arab Emirates', '+971'),
    (UUID(), 'United Kingdom', '+44'),
    (UUID(), 'United States', '+1'),
    (UUID(), 'Uruguay', '+598'),
    (UUID(), 'Uzbekistan', '+998'),
    (UUID(), 'Vanuatu', '+678'),
    (UUID(), 'Vatican City', '+379'),
    (UUID(), 'Venezuela', '+58'),
    (UUID(), 'Vietnam', '+84'),
    (UUID(), 'Yemen', '+967'),
    (UUID(), 'Zambia', '+260'),
    (UUID(), 'Zimbabwe', '+263');