CREATE TABLE `country_codes` (
    `id` CHAR(36) NOT NULL PRIMARY KEY DEFAULT (UUID()),
    `country_name` VARCHAR(100) NOT NULL,
    `country_code` VARCHAR(10) NOT NULL
);

INSERT INTO `country_codes` (`country_name`, `country_code`) VALUES('Afghanistan', '+93');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Albania', '+355');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Algeria', '+213');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Andorra', '+376');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Angola', '+244');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Antigua and Barbuda', '+1-268');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Argentina', '+54');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Armenia', '+374');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Australia', '+61');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Austria', '+43');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Azerbaijan', '+994');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Bahamas', '+1-242');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Bahrain', '+973');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Bangladesh', '+880');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Barbados', '+1-246');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Belarus', '+375');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Belgium', '+32');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Belize', '+501');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Benin', '+229');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Bhutan', '+975');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Bolivia', '+591');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Bosnia and Herzegovina', '+387');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Botswana', '+267');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Brazil', '+55');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Brunei', '+673');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Bulgaria', '+359');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Burkina Faso', '+226');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Burundi', '+257');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Cabo Verde', '+238');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Cambodia', '+855');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Cameroon', '+237');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Canada', '+1');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Central African Republic', '+236');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Chad', '+235');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Chile', '+56');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('China', '+86');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Colombia', '+57');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Comoros', '+269');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Congo, Democratic Republic of the', '+243');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Congo, Republic of the', '+242');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Costa Rica', '+506');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Croatia', '+385');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Cuba', '+53');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Cyprus', '+357');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Czech Republic', '+420');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Denmark', '+45');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Djibouti', '+253');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Dominica', '+1-767');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Dominican Republic', '+1-809');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('East Timor', '+670');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Ecuador', '+593');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Egypt', '+20');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('El Salvador', '+503');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Equatorial Guinea', '+240');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Eritrea', '+291');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Estonia', '+372');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Eswatini', '+268');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Ethiopia', '+251');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Fiji', '+679');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Finland', '+358');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('France', '+33');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Gabon', '+241');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Gambia', '+220');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Georgia', '+995');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Germany', '+49');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Ghana', '+233');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Greece', '+30');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Grenada', '+1-473');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Guatemala', '+502');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Guinea', '+224');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Guinea-Bissau', '+245');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Guyana', '+592');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Haiti', '+509');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Honduras', '+504');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Hungary', '+36');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Iceland', '+354');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('India', '+91');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Indonesia', '+62');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Iran', '+98');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Iraq', '+964');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Ireland', '+353');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Israel', '+972');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Italy', '+39');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Jamaica', '+1-876');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Japan', '+81');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Jordan', '+962');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Kazakhstan', '+7');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Kenya', '+254');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Kiribati', '+686');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Korea, North', '+850');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Korea, South', '+82');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Kosovo', '+383');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Kuwait', '+965');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Kyrgyzstan', '+996');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Laos', '+856');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Latvia', '+371');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Lebanon', '+961');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Lesotho', '+266');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Liberia', '+231');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Libya', '+218');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Liechtenstein', '+423');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Lithuania', '+370');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Luxembourg', '+352');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Madagascar', '+261');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Malawi', '+265');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Malaysia', '+60');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Maldives', '+960');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Mali', '+223');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Malta', '+356');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Marshall Islands', '+692');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Mauritania', '+222');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Mauritius', '+230');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Mexico', '+52');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Micronesia', '+691');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Moldova', '+373');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Monaco', '+377');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Mongolia', '+976');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Montenegro', '+382');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Morocco', '+212');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Mozambique', '+258');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Myanmar', '+95');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Namibia', '+264');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Nauru', '+674');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Nepal', '+977');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Netherlands', '+31');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('New Zealand', '+64');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Nicaragua', '+505');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Niger', '+227');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Nigeria', '+234');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('North Macedonia', '+389');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Norway', '+47');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Oman', '+968');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Pakistan', '+92');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Palau', '+680');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Palestine', '+970');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Panama', '+507');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Papua New Guinea', '+675');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Paraguay', '+595');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Peru', '+51');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Philippines', '+63');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Poland', '+48');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Portugal', '+351');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Qatar', '+974');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Romania', '+40');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Russia', '+7');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Rwanda', '+250');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Saint Kitts and Nevis', '+1-869');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Saint Lucia', '+1-758');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Saint Vincent and the Grenadines', '+1-784');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Samoa', '+685');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('San Marino', '+378');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Sao Tome and Principe', '+239');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Saudi Arabia', '+966');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Senegal', '+221');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Serbia', '+381');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Seychelles', '+248');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Sierra Leone', '+232');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Singapore', '+65');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Slovakia', '+421');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Slovenia', '+386');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Solomon Islands', '+677');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Somalia', '+252');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('South Africa', '+27');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('South Sudan', '+211');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Spain', '+34');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Sri Lanka', '+94');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Sudan', '+249');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Suriname', '+597');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Sweden', '+46');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Switzerland', '+41');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Syria', '+963');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Taiwan', '+886');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Tajikistan', '+992');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Tanzania', '+255');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Thailand', '+66');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Togo', '+228');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Tonga', '+676');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Trinidad and Tobago', '+1-868');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Tunisia', '+216');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Turkey', '+90');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Turkmenistan', '+993');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Tuvalu', '+688');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Uganda', '+256');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Ukraine', '+380');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('United Arab Emirates', '+971');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('United Kingdom', '+44');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('United States', '+1');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Uruguay', '+598');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Uzbekistan', '+998');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Vanuatu', '+678');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Vatican City', '+379');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Venezuela', '+58');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Vietnam', '+84');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Yemen', '+967');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Zambia', '+260');
INSERT INTO `country_codes` (`country_name`, `country_code`) Values('Zimbabwe', '+263');